config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: %i(show new create)
  resources :books, only: %i(index show)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books
  has_many :books, through: :author_books
  has_many :passive_relationships, as: :followable
  has_many :followers, through: :passive_relationships, source: :follower
  scope :newest, ->{order :created_at}
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  belongs_to :category
  has_many :request_details
  has_many :passive_relationships, as: :followable
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites
  has_many :comments, as: :commentable
  has_many :author_books
  has_many :authors, through: :author_books

  delegate :name, to: :category, prefix: :category
  delegate :name, to: :publisher, prefix: :publisher

  scope :newest, ->{order :created_at}
  scope :name_like, ->(name){where "name LIKE ?", "%#{name}%" if name.present?}
  accepts_nested_attributes_for :author_books

  def writers
    authors.map(&:name).join(", ")
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followable, polymorphic: true

  validates :follower_id, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :request_details

  enum status: {pending: 0, approved: 1, cancel: 2, reject: 3}
end

app/models/request_detail.rb
class RequestDetail < ApplicationRecord
  belongs_to :book
  belongs_to :request

  enum status: {pending: 0, approved: 1, cancel: 2, reject: 3}
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_accessor :remember_token

  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name:  Relationship.name,
                                  foreign_key: :follower_id,
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  Relationship.name,
                                   foreign_key: :followable_id,
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followable
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :following_books, through: :active_relationships,
   source: :followable, source_type: "Book"
  has_many :following_authors, through: :active_relationships,
    source: :followable, source_type: "Author"
  has_many :favorites, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_secure_password

  enum role: {user: 0, admin: 1}, _suffix: true
  enum gender: {male: 0, female: 1}

  validates :name, presence: true,
    length: {maximum: Settings.maximum_name_length}
  validates :email, presence: true,
    length: {maximum: Settings.maximum_email_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: Settings.minimum_password_length}, allow_nil: true
  validates :address, presence: true,
    length: {maximum: Settings.maximum_address_length}

  before_save :downcase_email

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end
  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send("#{attribute}_digest")
    return false unless digest
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute :remember_digest, nil
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book, only: :show

  def index
    @books =
      Book.name_like(params[:search]).newest.paginate page: params[:page],
        per_page: Settings.book.per_page
  end

  def show; end

  private

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = t "messenger.no_data"
    render :index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by email: params[:session][:email].downcase
    if @user&.authenticate params[:session][:password]
      login_and_redirect @user
    else
      flash.now[:danger] = t "misc.login_fails"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

  private

  def remmember? user
    if params[:session][:remember_me] == Settings.remember_me
      remember user
    else
      forget user
    end
  end

  def login_and_redirect user
    log_in user
    remmember? user
    redirect_back_or user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, :load_user, only: :show

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      redirect_to @user
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :address, :birthday,
      :gender, :password, :password_confirmation
  end

  def load_user
    return @user if @user = User.find_by(id: params[:id])
    flash[:danger] = t "misc.user_not_exists"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = I18n.t "sun_library"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def load_categories_selectbox
    @category.map{|u| [u.name, u.id]}
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user&.authenticated? :remember, cookies[:remember_token]
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to(session[:forwarding_url] || default)
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.gravatar_size
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small class="created_by">
    <%= raw t("footer.created_by",
      href1: link_to(t("sun_library"), t("footer.link_sun")),
      href2: link_to(t("footer.name"), t("footer.link_name"))) %>
  </small>
  <nav>
    <ul class="hotline">
      <li><%= t "footer.hot_line" %></li>
    </ul>
  </nav>
  

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("sun_library"), root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("root"), root_path %></li>
        <li><%= link_to t("book"), books_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li><%= link_to t("settings"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("log_in"), login_path %></li>
        <% end %>
        <li>
          <%= render "layouts/search" %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_search.html.erb
<%= form_tag books_path, :method => "get" do %>
  <div class="active-cyan-4 mb-4">
    <%= text_field_tag :search, params[:search], class: "form-control",
      placeholder: t(".search") %>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "misc.error_message_html", error_count: t("misc.errors", count: object.errors.size) %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>